export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.bin:$PATH"

export VISUAL=nvim
export EDITOR="$VISUAL"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export ERL_AFLAGS="-kernel shell_history enabled -kernel shell_history_file_bytes 1024000"

export CLICOLOR=1
export DIRENV_LOG_FORMAT=

eval "$(mise activate zsh)"
