fpath=(/opt/homebrew/share/zsh-completions $fpath)
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

[[ -f $HOME/.zsh_local ]] && source $HOME/.zsh_local

for config in $HOME/.zsh/configs/*; do
  source $config
done

export DIRENV_LOG_FORMAT=
eval "$(direnv hook zsh)"

for _cmd in kubectl helm mise; do
  if [[ $commands[$_cmd] ]]; then
    _cache="$HOME/.zsh/cache/_$_cmd"
    if [[ ! -f "$_cache" || "$commands[$_cmd]" -nt "$_cache" ]]; then
      mkdir -p "${_cache:h}"
      $_cmd completion zsh > "$_cache"
    fi
    source "$_cache"
  fi
done
unset _cmd _cache
